### ISSUE TITLE
Linux Support

### ISSUE THREAD

**Issue by soumyaDghosh** [Shourya70073/PDF-READER#1]
Can I build this app in Linux? Apparently I am getting this error when building it in linux(Ubuntu 23.04)
```
[   +2 ms] CMake Error at
/snap/flutter/130/usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:463
(message):
[   +4 ms]   A required package was not found
[        ] Call Stack (most recent call first):
[        ] 
/snap/flutter/130/usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:643
(_pkg_check_modules_internal)
[        ] 
flutter/ephemeral/.plugin_symlinks/audioplayers_linux/linux/CMakeLists.txt:25
(pkg_check_modules)
```

**Comment by soumyaDghosh** [comment]
Okay to have this app build properly you need to have `libgstreamer1.0-dev` `libgstreamer-plugins-base1.0-dev` installed in your system. Package names may vary in different distros.

**Comment by soumyaDghosh** [comment]
```
[   +6 ms] [+7389 ms]
../.pub-cache/hosted/pub.dev/file-6.1.2/lib/src/interface/file.dart:15:16:
Error: The method 'File.create' has fewer named arguments than those of
overridden method 'File.create'.
[   +5 ms] [   +2 ms]   Future<File> create({bool recursive = false});
[   +1 ms] [        ]                ^
[   +2 ms] [        ]
org-dartlang-sdk:///third_party/dart/sdk/lib/io/file.dart:232:16: Context: This
is the overridden method ('create').
[   +1 ms] [        ]   Future<File> create({bool recursive = false, bool
exclusive = false});
[        ] [        ]                ^
[        ] [   +6 ms]
../.pub-cache/hosted/pub.dev/file-6.1.2/lib/src/interface/file.dart:15:16:
Error: The method 'File.create' doesn't have the named parameter 'exclusive' of
overridden method 'File.create'.
[        ] [        ]   Future<File> create({bool recursive = false});
[        ] [        ]                ^
[        ] [        ]
org-dartlang-sdk:///third_party/dart/sdk/lib/io/file.dart:232:16: Context: This
is the overridden method ('create').
[        ] [        ]   Future<File> create({bool recursive = false, bool
exclusive = false});
[        ] [        ]                ^
[        ] [        ]
../.pub-cache/hosted/pub.dev/file-6.1.2/lib/src/forwarding/forwarding_file.dart:
22:8: Error: The method 'ForwardingFile.createSync' has fewer named arguments
than those of overridden method 'File.createSync'.
[        ] [        ]   void createSync({bool recursive = false}) =>
[        ] [        ]        ^
[        ] [        ]
org-dartlang-sdk:///third_party/dart/sdk/lib/io/file.dart:248:8: Context: This
is the overridden method ('createSync').
[        ] [        ]   void createSync({bool recursive = false, bool exclusive
= false});
[        ] [        ]        ^
[        ] [        ]
../.pub-cache/hosted/pub.dev/file-6.1.2/lib/src/forwarding/forwarding_file.dart:
22:8: Error: The method 'ForwardingFile.createSync' doesn't have the named
parameter 'exclusive' of overridden method 'File.createSync'.
[        ] [        ]   void createSync({bool recursive = false}) =>
[        ] [        ]        ^
[        ] [        ]
org-dartlang-sdk:///third_party/dart/sdk/lib/io/file.dart:248:8: Context: This
is the overridden method ('createSync').
[        ] [        ]   void createSync({bool recursive = false, bool exclusive
= false});
[        ] [        ]        ^
[        ] [+5118 ms] lib/screens/homepage.dart:72:32: Error: The method
'RaisedButton' isn't defined for the class '_homepageState'.
[        ] [        ]  - '_homepageState' is from
'package:internshiptask/screens/homepage.dart' ('lib/screens/homepage.dart').
[        ] [        ] Try correcting the name to the name of an existing method,
or defining a method named 'RaisedButton'.
[        ] [        ]                         child: RaisedButton(
[        ] [        ]                                ^^^^^^^^^^^^
[        ] [+2163 ms] lib/pdf__reader/pdf.dart:92:35: Error: The method
'RaisedButton' isn't defined for the class '_pdfState'.
[        ] [        ]  - '_pdfState' is from
'package:internshiptask/pdf__reader/pdf.dart' ('lib/pdf__reader/pdf.dart').
[        ] [        ] Try correcting the name to the name of an existing method,
or defining a method named 'RaisedButton'.
[        ] [        ]                                   RaisedButton(
[        ] [        ]                                   ^^^^^^^^^^^^
[        ] [        ] lib/pdf__reader/pdf.dart:115:35: Error: The method
'RaisedButton' isn't defined for the class '_pdfState'.
[        ] [        ]  - '_pdfState' is from
'package:internshiptask/pdf__reader/pdf.dart' ('lib/pdf__reader/pdf.dart').
[        ] [        ] Try correcting the name to the name of an existing method,
or defining a method named 'RaisedButton'.
[        ] [        ]                                   RaisedButton(
[        ] [        ]                                   ^^^^^^^^^^^^
[        ] [+16860 ms] Persisting file store
[        ] [   +8 ms] Done persisting file store
[        ] [   +8 ms] Target kernel_snapshot failed: Exception
[        ]            #0      KernelSnapshot.build
(package:flutter_tools/src/build_system/targets/common.dart:246:7)
[        ]            <asynchronous suspension>
[        ]            #1      _BuildInstance._invokeInternal
(package:flutter_tools/src/build_system/build_system.dart:847:9)
[        ]            <asynchronous suspension>
[        ]            #2      Future.wait.<anonymous closure>
(dart:async/future.dart:522:21)
[   +1 ms]            <asynchronous suspension>
[        ]            #3      _BuildInstance.invokeTarget
(package:flutter_tools/src/build_system/build_system.dart:785:32)
[        ]            <asynchronous suspension>
[        ]            #4      FlutterBuildSystem.build
(package:flutter_tools/src/build_system/build_system.dart:614:16)
[        ]            <asynchronous suspension>
[        ]            #5      AssembleCommand.runCommand
(package:flutter_tools/src/commands/assemble.dart:337:32)
[        ]            <asynchronous suspension>
[        ]            #6      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1257:27)
[        ]            <asynchronous suspension>
[        ]            #7      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #8      CommandRunner.runCommand
(package:args/command_runner.dart:209:13)
[        ]            <asynchronous suspension>
[        ]            #9      FlutterCommandRunner.runCommand.<anonymous
closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
[        ]            <asynchronous suspension>
[        ]            #10     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #11     FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
[        ]            <asynchronous suspension>
[        ]            #12     run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:64:9)
[        ]            <asynchronous suspension>
[        ]            #13     AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #14     main (package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[        ] [  +31 ms] "flutter assemble" took 33,696ms.
[        ] [  +13 ms] 
[        ]            #0      throwToolExit
(package:flutter_tools/src/base/common.dart:10:3)
[        ]            #1      AssembleCommand.runCommand
(package:flutter_tools/src/commands/assemble.dart:354:7)
[        ]            <asynchronous suspension>
[        ]            #2      FlutterCommand.run.<anonymous closure>
(package:flutter_tools/src/runner/flutter_command.dart:1257:27)
[        ]            <asynchronous suspension>
[        ]            #3      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #4      CommandRunner.runCommand
(package:args/command_runner.dart:209:13)
[        ]            <asynchronous suspension>
[        ]            #5      FlutterCommandRunner.runCommand.<anonymous
closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
[        ]            <asynchronous suspension>
[        ]            #6      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #7      FlutterCommandRunner.runCommand
(package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
[        ]            <asynchronous suspension>
[        ]            #8      run.<anonymous closure>.<anonymous closure>
(package:flutter_tools/runner.dart:64:9)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure>
(package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #10     main (package:flutter_tools/executable.dart:91:3)
[        ]            <asynchronous suspension>
[        ] [ +253 ms] ensureAnalyticsSent: 251ms
[        ] [        ] Running 0 shutdown hooks
[        ] [        ] Shutdown hooks complete
[        ] [        ] exiting with code 1
[        ] ninja: build stopped: subcommand failed.
[  +34 ms] Building Linux application... (completed in 36.7s)
[   +1 ms] Exception: Build process failed
[   +9 ms] "flutter run" took 38,236ms.
[   +9 ms] 
           #0      throwToolExit
(package:flutter_tools/src/base/common.dart:10:3)
           #1      RunCommand.runCommand
           (package:flutter_tools/src/commands/run.dart:722:9)
           <asynchronous suspension>
           #2      FlutterCommand.run.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command.dart:1257:27)
           <asynchronous suspension>
           #3      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #4      CommandRunner.runCommand
(package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #5      FlutterCommandRunner.runCommand.<anonymous closure>
           (package:flutter_tools/src/runner/flutter_command_runner.dart:283:9)
           <asynchronous suspension>
           #6      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand
           (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #8      run.<anonymous closure>.<anonymous closure>
           (package:flutter_tools/runner.dart:64:9)
           <asynchronous suspension>
           #9      AppContext.run.<anonymous closure>
           (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #10     main (package:flutter_tools/executable.dart:91:3)
           <asynchronous suspension>
           
```
